CREATE SCHEMA IF NOT EXISTS sigmat;

CREATE TYPE sigmat.perfil_usuario AS ENUM (
    'operador',
    'administrador',
    'visualizador'
);

CREATE TYPE sigmat.tiposervidor AS ENUM (
    'GUARDA',
    'DMTT'
);

CREATE TYPE sigmat.situacao_servidor AS ENUM (
    'ativo',
    'inativo',
    'afastado'
);

CREATE TABLE sigmat.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    usuario TEXT UNIQUE,
    telefone TEXT,
    perfil sigmat.perfil_usuario NOT NULL DEFAULT 'operador',
    senha_hash TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sigmat.usuario_sessao (
	usuario_id int4 NOT NULL,
	"token" varchar(64) NOT NULL,
	criado_em timestamptz DEFAULT now() NOT NULL,
	ultimo_acesso timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT usuario_sessao_pkey PRIMARY KEY (usuario_id)
);
ALTER TABLE sigmat.usuario_sessao ADD CONSTRAINT usuario_sessao_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES sigmat.usuario(id) ON DELETE CASCADE;


CREATE TABLE sigmat.servidor (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo sigmat.tiposervidor NOT NULL,
	nome text NOT NULL,
	matricula varchar(20) NOT NULL,
	cpf varchar(14) NOT NULL,
	rg text NULL,
	naturalidade text NULL,
	data_nascimento date NULL,
	filiacao_pai text NULL,
	filiacao_mae text NULL,
	cargo text NOT NULL,
	data_admissao date NULL,
	data_emissao date NULL,
	data_validade date NULL,
	fe_publica text NULL,
	porte_arma bool DEFAULT false NOT NULL,
	tipo_sanguineo varchar(5) NULL,
	foto_url text NULL,
	assinatura_url text NULL,
	situacao sigmat.situacao_servidor DEFAULT 'ativo'::sigmat.situacao_servidor NOT NULL,
	ativo bool DEFAULT true NOT NULL,
	criado_em timestamptz DEFAULT now() NOT NULL,
	atualizado_em timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT servidor_cpf_uk UNIQUE (cpf),
	CONSTRAINT servidor_matricula_uk UNIQUE (matricula),
	CONSTRAINT servidor_pkey PRIMARY KEY (id)
);